### ISSUE TITLE
Error on uploading multiple files

### ISSUE THREAD

**Issue by puroong** [chunkai1312/multer-sftp#9]
Everytime I try to upload multiple files at once,

I get `No SFTP connection available` & `An existing SFTP connection is already defined` error from ssh2-sftp

resulting some sftp connection errors

Could I get some help?

It works well when I only upload single file though

- version
  - multer-sftp: 1.1.0
  - ssh2-sftp-client: 5.2.1

```
const sftpStorage = require("multer-sftp");
const sftpConfig = require("../../config/sftp");

const storage = sftpStorage({
	sftp: {
		host: sftpConfig.sftp.host,
		port: 22,
		username: sftpConfig.sftp.username,
		password: sftpConfig.sftp.password
	},
	destination: function (req, file, cb) {
		cb(null, sftpConfig.sftp.destination);
	}
});

const upload = multer({ storage: storage, limits: { fileSize: 5 * 1024 * 1024 }}).array("attachments", 10);

app.post("/test", upload, async function() {
.
.
.
```

```
(node:89521) UnhandledPromiseRejectionWarning: Error: end: No SFTP connection available
    at formatError (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Object.haveConnection (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:627:20)
    at Promise (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:1318:19)
    at new Promise (<anonymous>)
    at SftpClient.end (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:1305:12)
    at client.connect.then.then.catch.then (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:53:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:89521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:89521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: connect: An existing SFTP connection is already defined
    at Object.formatError (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Promise (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:140:17)
    at new Promise (<anonymous>)
    at SftpClient.connect (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:137:12)
    at getFilename (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:45:19)
    at AsyncWrap.<anonymous> (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:9:5)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8) code: 'ERR_NOT_CONNECTED', custom: true, storageErrors: [] }
```

**Comment by puroong** [comment]
Asychronous call seems to be causing problem

I think Promise.all would be the best solution except that we can't use it since _handleFile accepts file one by one

How do you think about instatiating new sftp client on each _handleFile call?

```
connect: 7ad23d0f15431ff6aafe09edaf0fbb9b
first promise: 7ad23d0f15431ff6aafe09edaf0fbb9b
connect: 0bbd02677ce90bdd277de622553ef243

##############
error log

{ Error: connect: An existing SFTP connection is already defined
    at Object.formatError (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Promise (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:140:17)
    at new Promise (<anonymous>)
    at SftpClient.connect (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:137:12)
    at getFilename (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:46:19)
    at AsyncWrap.<anonymous> (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:9:5)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8) code: 'ERR_NOT_CONNECTED', custom: true }
###############

end: 0bbd02677ce90bdd277de622553ef243

##############
error log

{ Error: put: Connection closed unepectedly
    at formatError (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Client.<anonymous> (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:134:16)
    at Client.emit (events.js:203:15)
    at Socket.<anonymous> (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2/lib/client.js:317:10)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:607:12) code: 'ERR_GENERIC_CLIENT', custom: true }
###############

end: 7ad23d0f15431ff6aafe09edaf0fbb9b
(node:108246) UnhandledPromiseRejectionWarning: Error: end: No SFTP connection available
    at formatError (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Object.haveConnection (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:627:20)
    at Promise (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:1318:19)
    at new Promise (<anonymous>)
    at SftpClient.end (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:1305:12)
    at client.connect.then.then.catch.then (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:67:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:108246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:108246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: connect: An existing SFTP connection is already defined
    at Object.formatError (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Promise (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:140:17)
    at new Promise (<anonymous>)
    at SftpClient.connect (/home/nostalgia/Projects/wherehouse-backend/node_modules/ssh2-sftp-client/src/index.js:137:12)
    at getFilename (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:46:19)
    at AsyncWrap.<anonymous> (/home/nostalgia/Projects/wherehouse-backend/node_modules/multer-sftp/lib/index.js:9:5)
    at AsyncWrap.wrap.ondone (internal/crypto/random.js:57:8) code: 'ERR_NOT_CONNECTED', custom: true, storageErrors: [] }
```
